### ISSUE TITLE
Is python library available for IAM authentication for MSK?

### ISSUE THREAD

**Issue by ams45** [aws/aws-msk-iam-auth#65] opened 2022-05-02 11:17 UTC
Is python library available for IAM authentication for MSK? 

I wanted to try to write kafka producer using python with IAM role authentication. 
Does anyone know if any API/sdk is available in python?

**Comment by OneCricketeer** [comment] 2022-05-14 13:00
Related #10

**Comment by gokul2411s** [comment] 2022-05-16 16:20
Closing as duplicate of #10 .

**Closed by gokul2411s** 2022-05-16 16:20 UTC

**Comment by van4oza** [comment] 2023-02-02 14:03
kafka-python + SASL auth MSK worker for me

```
producer = KafkaProducer(
    bootstrap_servers=SASL_SERVERS,
    value_serializer=lambda v: json.dumps(v).encode('utf-8'),
    api_version=(2,8,1),
    security_protocol='SASL_SSL',
    sasl_mechanism='SCRAM-SHA-512',
    sasl_plain_username=os.getenv('KAFKA_USER'),
    sasl_plain_password=os.getenv('KAFKA_PASS'),
    retries=1
)
```

**Comment by aidan-melen** [comment] 2023-02-03 16:41
> kafka-python + SASL auth MSK worker for me
> 
> ```
> producer = KafkaProducer(
>     bootstrap_servers=SASL_SERVERS,
>     value_serializer=lambda v: json.dumps(v).encode('utf-8'),
>     api_version=(2,8,1),
>     security_protocol='SASL_SSL',
>     sasl_mechanism='SCRAM-SHA-512',
>     sasl_plain_username=os.getenv('KAFKA_USER'),
>     sasl_plain_password=os.getenv('KAFKA_PASS'),
>     retries=1
> )
> ```

I think the OP is more interested in SASL/IAM support
